services:

  caldera:
    build:
      context: ./caldera
      args:
        - VARIANT=full
    container_name: caldera
    ports:
      - "8888:8888"
      - "8443:8443"
      - "7010:7010"
      - "7011:7011/udp"
      - "7012:7012"
      - "8853:8853"
      - "8022:8022"
      - "2222:2222"
    command: --log DEBUG

  alloy:
    image: grafana/alloy:latest
    container_name: alloy-attack
    user: '0'
    ports:
      - 3000:3000
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy
      - /var/run/docker.sock:/var/run/docker.sock
    command: >
      run --server.http.listen-addr=0.0.0.0:3000 --storage.path=/var/lib/alloy/data 
      /etc/alloy/config.alloy

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    container_name: cadvisor-attack
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    ports:
      - "3100:8080"
    privileged: true
    devices:
      - /dev/kmsg
    restart: unless-stopped