services:

  frontend:
    build: ./Frontend/red-box
    image: isab3ll/management:frontend
    ports:
      - "5173:5173"
    environment:
      - PUBLIC_BACKEND_IP=192.168.0.28
      - PUBLIC_BACKEND_PORT=8000
      - PUBLIC_ATTACK_IP=192.168.0.25
      - PUBLIC_ATTACK_PORT=8888

  backend:
    build: ./Backend
    image: isab3ll/management:backend
    ports:
      - "8000:8000"
    environment:
      - FRONTEND_IP=192.168.0.28
      - FRONTEND_PORT=5173
    volumes:
      - /root/.ssh:/root/.ssh:ro