filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

filebeat.modules:
  - module: system
    period: 10s
    metricsets:
      - cpu
      - load
      - memory
      - network
      - process
      - process_summary
      - core
      - diskio
      - socket
    syslog:
      enabled: true

processors:
- add_cloud_metadata: ~

output.elasticsearch:
  hosts: ['http://192.168.0.27:9200']
  username: 'elastic'
  password: 'elastic'
  ssl.verification_mode: 'none'

setup.kibana:
  host: "http://192.168.0.27:5601"

logging.level: debug
logging.to_stderr: true
